// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023204443_AddCOllumnActive")]
    partial class AddCOllumnActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8221),
                            Name = "Multilaser",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8224)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8239),
                            Name = "Philco",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8239)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8241),
                            Name = "Gradiente",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8241)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8243),
                            Name = "Mondial",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8243)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8245),
                            Name = "Fischer",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8245)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8247),
                            Name = "Cadence",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8247)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8248),
                            Name = "Britânia",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8248)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8250),
                            Name = "Lenoxx",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8250)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8251),
                            Name = "Arno",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8251)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8252),
                            Name = "Oster",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8253)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8254),
                            Name = "Black+Decker",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8255)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8256),
                            Name = "Easynvest",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8256)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8257),
                            Name = "Fischer",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8258)
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8259),
                            Name = "Mondial",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8259)
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8260),
                            Name = "Cadence",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8260)
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8262),
                            Name = "Britânia",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8262)
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8264),
                            Name = "Arno",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8264)
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8265),
                            Name = "Oster",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8265)
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8267),
                            Name = "Lenoxx",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8267)
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8268),
                            Name = "Philco",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8268)
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8270),
                            Name = "Multilaser",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8271),
                            Name = "Gradiente",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8272)
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8273),
                            Name = "Cuisinart",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8273)
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8274),
                            Name = "Tramontina",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8275)
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8276),
                            Name = "Samsung Brasil",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8276)
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8278),
                            Name = "LG Brasil",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8278)
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8279),
                            Name = "Intelbras",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8280)
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8281),
                            Name = "Philips Brasil",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8281)
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8282),
                            Name = "HP Brasil",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8283)
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8284),
                            Name = "Lenovo Brasil",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 847, DateTimeKind.Utc).AddTicks(8284)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1026),
                            Name = "Informática",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1027)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1040),
                            Name = "Eletroportáteis",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1040)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1042),
                            Name = "Áudio e Vídeo",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1042)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1044),
                            Name = "Culinária e Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1044)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1046),
                            Name = "Esporte e Fitness",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1046)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1113),
                            Name = "Eletrodomésticos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1113)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1115),
                            Name = "Climatização",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1116)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1117),
                            Name = "Som e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1118)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1120),
                            Name = "Pequenos Eletrodomésticos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1120)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1123),
                            Name = "Utensílios de Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1123)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1126),
                            Name = "Telefonia",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1126)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1128),
                            Name = "Telefonia Móvel",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1128)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1129),
                            Name = "Smartphones",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1131),
                            Name = "Tablets",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1131)
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1133),
                            Name = "Acessórios de Celular",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1133)
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1134),
                            Name = "Monitores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1134)
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1136),
                            Name = "Notebooks",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1136)
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1139),
                            Name = "Computadores Desktop",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1139)
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1140),
                            Name = "Periféricos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1141)
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1142),
                            Name = "Cadeiras e Mesas Gamer",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1142)
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1144),
                            Name = "TVs e Home Theater",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1144)
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1145),
                            Name = "Projetores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1146)
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1147),
                            Name = "Câmeras e Filmadoras",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1147)
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1148),
                            Name = "Fotografia e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1149)
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1150),
                            Name = "Consoles e Jogos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1150)
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1152),
                            Name = "Brinquedos Eletrônicos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1152)
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1153),
                            Name = "Fones de Ouvido",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1153)
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1155),
                            Name = "Caixas de Som",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1155)
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1157),
                            Name = "Relógios Inteligentes",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1157)
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1158),
                            Name = "Carregadores e Cabos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1158)
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1160),
                            Name = "Móveis para Escritório",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1160)
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1161),
                            Name = "Móveis para Sala",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1162)
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1163),
                            Name = "Móveis para Quarto",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1163)
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1166),
                            Name = "Móveis para Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1166)
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1168),
                            Name = "Decoração",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1168)
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1169),
                            Name = "Iluminação",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1170)
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1171),
                            Name = "Cama, Mesa e Banho",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1171)
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1172),
                            Name = "Roupas Masculinas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1173)
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1174),
                            Name = "Roupas Femininas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1174)
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1175),
                            Name = "Roupas Infantis",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1176)
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1177),
                            Name = "Calçados",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1177)
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1178),
                            Name = "Bolsas e Mochilas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1179)
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1180),
                            Name = "Bijuterias e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1180)
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1182),
                            Name = "Beleza e Cosméticos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1182)
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1183),
                            Name = "Perfumaria",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1184)
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1185),
                            Name = "Saúde e Bem-estar",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1185)
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1186),
                            Name = "Suplementos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1187)
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1188),
                            Name = "Alimentos e Bebidas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1188)
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1190),
                            Name = "Hortifruti",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1190)
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1191),
                            Name = "Padaria e Confeitaria",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1192)
                        },
                        new
                        {
                            Id = 51L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1193),
                            Name = "Utensílios Domésticos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1193)
                        },
                        new
                        {
                            Id = 52L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1194),
                            Name = "Ferramentas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1195)
                        },
                        new
                        {
                            Id = 53L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1196),
                            Name = "Materiais de Construção",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1196)
                        },
                        new
                        {
                            Id = 54L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1198),
                            Name = "Automotivo",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1198)
                        },
                        new
                        {
                            Id = 55L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1199),
                            Name = "Moto e Bicicleta",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1199)
                        },
                        new
                        {
                            Id = 56L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1201),
                            Name = "Brinquedos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1201)
                        },
                        new
                        {
                            Id = 57L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1202),
                            Name = "Games e Consoles",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1203)
                        },
                        new
                        {
                            Id = 58L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1204),
                            Name = "Papéis e Escritório",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1204)
                        },
                        new
                        {
                            Id = 59L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1206),
                            Name = "Eletrônicos de Carro",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1206)
                        },
                        new
                        {
                            Id = 60L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1207),
                            Name = "Roupas Íntimas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1207)
                        },
                        new
                        {
                            Id = 61L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1209),
                            Name = "Produtos Pet",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1209)
                        },
                        new
                        {
                            Id = 62L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1210),
                            Name = "Acessórios para Animais",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1211)
                        },
                        new
                        {
                            Id = 63L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1212),
                            Name = "Jardinagem",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1212)
                        },
                        new
                        {
                            Id = 64L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1214),
                            Name = "Ferramentas Elétricas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1214)
                        },
                        new
                        {
                            Id = 65L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1215),
                            Name = "Segurança Residencial",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1215)
                        },
                        new
                        {
                            Id = 66L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1219),
                            Name = "Câmeras de Segurança",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1219)
                        },
                        new
                        {
                            Id = 67L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1220),
                            Name = "Iluminação Inteligente",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1220)
                        },
                        new
                        {
                            Id = 68L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1222),
                            Name = "Ar Condicionado",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1222)
                        },
                        new
                        {
                            Id = 69L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1223),
                            Name = "Ventiladores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1224)
                        },
                        new
                        {
                            Id = 70L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1225),
                            Name = "Aquecedores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1225)
                        },
                        new
                        {
                            Id = 71L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1226),
                            Name = "Micro-ondas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1227)
                        },
                        new
                        {
                            Id = 72L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1228),
                            Name = "Geladeiras",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1228)
                        },
                        new
                        {
                            Id = 73L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1230),
                            Name = "Freezers",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1230)
                        },
                        new
                        {
                            Id = 74L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1231),
                            Name = "Fogões e Cooktops",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1232)
                        },
                        new
                        {
                            Id = 75L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1233),
                            Name = "Lavadoras de Roupas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1233)
                        },
                        new
                        {
                            Id = 76L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1273),
                            Name = "Secadoras de Roupas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1274)
                        },
                        new
                        {
                            Id = 77L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1275),
                            Name = "Máquinas de Lavar Louça",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1276)
                        },
                        new
                        {
                            Id = 78L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1277),
                            Name = "Fritadeiras e Air Fryers",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1277)
                        },
                        new
                        {
                            Id = 79L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1278),
                            Name = "Liquidificadores e Batedeiras",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1279)
                        },
                        new
                        {
                            Id = 80L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1280),
                            Name = "Cafeteiras e Chaleiras",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1280)
                        },
                        new
                        {
                            Id = 81L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1282),
                            Name = "Panelas Elétricas",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1282)
                        },
                        new
                        {
                            Id = 82L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1283),
                            Name = "Aparelhos de Pressão e Massageadores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1284)
                        },
                        new
                        {
                            Id = 83L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1285),
                            Name = "Rastreador de Atividades",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1285)
                        },
                        new
                        {
                            Id = 84L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1286),
                            Name = "Fones Bluetooth",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1287)
                        },
                        new
                        {
                            Id = 85L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1288),
                            Name = "Caixas de Som Portáteis",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1288)
                        },
                        new
                        {
                            Id = 86L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1289),
                            Name = "Adaptadores e Cabos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1290)
                        },
                        new
                        {
                            Id = 87L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1291),
                            Name = "Memórias e Pen Drives",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1291)
                        },
                        new
                        {
                            Id = 88L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1292),
                            Name = "Placas de Vídeo",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1293)
                        },
                        new
                        {
                            Id = 89L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1294),
                            Name = "Processadores",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1294)
                        },
                        new
                        {
                            Id = 90L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1296),
                            Name = "Placas Mãe",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1296)
                        },
                        new
                        {
                            Id = 91L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1297),
                            Name = "Roteadores e Modems",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1297)
                        },
                        new
                        {
                            Id = 92L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1298),
                            Name = "Smart Home",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1299)
                        },
                        new
                        {
                            Id = 93L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1300),
                            Name = "Dispositivos IoT",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1300)
                        },
                        new
                        {
                            Id = 94L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1301),
                            Name = "Produtos Educacionais",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1302)
                        },
                        new
                        {
                            Id = 95L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1303),
                            Name = "Instrumentos Musicais",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1304)
                        },
                        new
                        {
                            Id = 96L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1305),
                            Name = "Material Escolar",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1305)
                        },
                        new
                        {
                            Id = 97L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1306),
                            Name = "Agenda e Planner",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1307)
                        },
                        new
                        {
                            Id = 98L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1308),
                            Name = "Cadernos e Blocos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1308)
                        },
                        new
                        {
                            Id = 99L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1310),
                            Name = "Artigos de Papelaria",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1310)
                        },
                        new
                        {
                            Id = 100L,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1311),
                            Name = "Kits e Combos",
                            UpdatedAt = new DateTime(2025, 10, 23, 20, 44, 42, 848, DateTimeKind.Utc).AddTicks(1311)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("product_category", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("product_category", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("product_category", b =>
                {
                    b.HasOne("Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
