// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1260),
                            Name = "Multilaser",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1262)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1271),
                            Name = "Philco",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1271)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1273),
                            Name = "Gradiente",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1273)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1275),
                            Name = "Mondial",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1275)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1276),
                            Name = "Fischer",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1277)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1277),
                            Name = "Cadence",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1278)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1279),
                            Name = "Britânia",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1279)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1280),
                            Name = "Lenoxx",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1280)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1281),
                            Name = "Arno",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1281)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1282),
                            Name = "Oster",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1283)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1284),
                            Name = "Black+Decker",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1284)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1334),
                            Name = "Easynvest",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1334)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1335),
                            Name = "Fischer",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1335)
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1336),
                            Name = "Mondial",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1336)
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1337),
                            Name = "Cadence",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1338)
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1338),
                            Name = "Britânia",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1339)
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1340),
                            Name = "Arno",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1340)
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1341),
                            Name = "Oster",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1341)
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1342),
                            Name = "Lenoxx",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1342)
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1343),
                            Name = "Philco",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1343)
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1344),
                            Name = "Multilaser",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1345)
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1345),
                            Name = "Gradiente",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1346)
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1347),
                            Name = "Cuisinart",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1347)
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1348),
                            Name = "Tramontina",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1348)
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1349),
                            Name = "Samsung Brasil",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1349)
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1350),
                            Name = "LG Brasil",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1350)
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1351),
                            Name = "Intelbras",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1351)
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1352),
                            Name = "Philips Brasil",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1352)
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1353),
                            Name = "HP Brasil",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1353)
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1354),
                            Name = "Lenovo Brasil",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(1354)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3373),
                            Name = "Informática",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3374)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3381),
                            Name = "Eletroportáteis",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3381)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3383),
                            Name = "Áudio e Vídeo",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3383)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3385),
                            Name = "Culinária e Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3385)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3386),
                            Name = "Esporte e Fitness",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3387)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3389),
                            Name = "Eletrodomésticos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3389)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3391),
                            Name = "Climatização",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3391)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3392),
                            Name = "Som e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3392)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3393),
                            Name = "Pequenos Eletrodomésticos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3394)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3395),
                            Name = "Utensílios de Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3395)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3396),
                            Name = "Telefonia",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3396)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3398),
                            Name = "Telefonia Móvel",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3398)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3399),
                            Name = "Smartphones",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3399)
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3400),
                            Name = "Tablets",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3400)
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3402),
                            Name = "Acessórios de Celular",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3402)
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3403),
                            Name = "Monitores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3403)
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3404),
                            Name = "Notebooks",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3404)
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3406),
                            Name = "Computadores Desktop",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3406)
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3407),
                            Name = "Periféricos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3407)
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3408),
                            Name = "Cadeiras e Mesas Gamer",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3408)
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3409),
                            Name = "TVs e Home Theater",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3409)
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3410),
                            Name = "Projetores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3411)
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3412),
                            Name = "Câmeras e Filmadoras",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3412)
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3444),
                            Name = "Fotografia e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3444)
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3445),
                            Name = "Consoles e Jogos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3445)
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3446),
                            Name = "Brinquedos Eletrônicos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3446)
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3447),
                            Name = "Fones de Ouvido",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3448)
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3449),
                            Name = "Caixas de Som",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3449)
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3450),
                            Name = "Relógios Inteligentes",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3450)
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3451),
                            Name = "Carregadores e Cabos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3451)
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3452),
                            Name = "Móveis para Escritório",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3452)
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3453),
                            Name = "Móveis para Sala",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3454)
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3455),
                            Name = "Móveis para Quarto",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3455)
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3456),
                            Name = "Móveis para Cozinha",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3457)
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3458),
                            Name = "Decoração",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3458)
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3459),
                            Name = "Iluminação",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3459)
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3460),
                            Name = "Cama, Mesa e Banho",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3460)
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3461),
                            Name = "Roupas Masculinas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3461)
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3462),
                            Name = "Roupas Femininas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3462)
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3463),
                            Name = "Roupas Infantis",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3464)
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3464),
                            Name = "Calçados",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3465)
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3466),
                            Name = "Bolsas e Mochilas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3466)
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3467),
                            Name = "Bijuterias e Acessórios",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3467)
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3468),
                            Name = "Beleza e Cosméticos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3468)
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3469),
                            Name = "Perfumaria",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3469)
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3470),
                            Name = "Saúde e Bem-estar",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3470)
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3471),
                            Name = "Suplementos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3472)
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3472),
                            Name = "Alimentos e Bebidas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3473)
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3474),
                            Name = "Hortifruti",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3474)
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3475),
                            Name = "Padaria e Confeitaria",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3475)
                        },
                        new
                        {
                            Id = 51L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3476),
                            Name = "Utensílios Domésticos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3476)
                        },
                        new
                        {
                            Id = 52L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3477),
                            Name = "Ferramentas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3478)
                        },
                        new
                        {
                            Id = 53L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3478),
                            Name = "Materiais de Construção",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3479)
                        },
                        new
                        {
                            Id = 54L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3480),
                            Name = "Automotivo",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3480)
                        },
                        new
                        {
                            Id = 55L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3481),
                            Name = "Moto e Bicicleta",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3481)
                        },
                        new
                        {
                            Id = 56L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3482),
                            Name = "Brinquedos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3482)
                        },
                        new
                        {
                            Id = 57L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3483),
                            Name = "Games e Consoles",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3484)
                        },
                        new
                        {
                            Id = 58L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3484),
                            Name = "Papéis e Escritório",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3485)
                        },
                        new
                        {
                            Id = 59L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3486),
                            Name = "Eletrônicos de Carro",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3486)
                        },
                        new
                        {
                            Id = 60L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3487),
                            Name = "Roupas Íntimas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3487)
                        },
                        new
                        {
                            Id = 61L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3488),
                            Name = "Produtos Pet",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3488)
                        },
                        new
                        {
                            Id = 62L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3489),
                            Name = "Acessórios para Animais",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3489)
                        },
                        new
                        {
                            Id = 63L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3490),
                            Name = "Jardinagem",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3491)
                        },
                        new
                        {
                            Id = 64L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3491),
                            Name = "Ferramentas Elétricas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3492)
                        },
                        new
                        {
                            Id = 65L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3493),
                            Name = "Segurança Residencial",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3493)
                        },
                        new
                        {
                            Id = 66L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3494),
                            Name = "Câmeras de Segurança",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3495)
                        },
                        new
                        {
                            Id = 67L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3496),
                            Name = "Iluminação Inteligente",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3496)
                        },
                        new
                        {
                            Id = 68L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3497),
                            Name = "Ar Condicionado",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3497)
                        },
                        new
                        {
                            Id = 69L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3498),
                            Name = "Ventiladores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3498)
                        },
                        new
                        {
                            Id = 70L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3499),
                            Name = "Aquecedores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3499)
                        },
                        new
                        {
                            Id = 71L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3500),
                            Name = "Micro-ondas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3500)
                        },
                        new
                        {
                            Id = 72L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3501),
                            Name = "Geladeiras",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3501)
                        },
                        new
                        {
                            Id = 73L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3502),
                            Name = "Freezers",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3503)
                        },
                        new
                        {
                            Id = 74L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3503),
                            Name = "Fogões e Cooktops",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3504)
                        },
                        new
                        {
                            Id = 75L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3505),
                            Name = "Lavadoras de Roupas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3505)
                        },
                        new
                        {
                            Id = 76L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3506),
                            Name = "Secadoras de Roupas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3506)
                        },
                        new
                        {
                            Id = 77L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3507),
                            Name = "Máquinas de Lavar Louça",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3507)
                        },
                        new
                        {
                            Id = 78L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3508),
                            Name = "Fritadeiras e Air Fryers",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3508)
                        },
                        new
                        {
                            Id = 79L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3509),
                            Name = "Liquidificadores e Batedeiras",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3510)
                        },
                        new
                        {
                            Id = 80L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3510),
                            Name = "Cafeteiras e Chaleiras",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3511)
                        },
                        new
                        {
                            Id = 81L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3512),
                            Name = "Panelas Elétricas",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3512)
                        },
                        new
                        {
                            Id = 82L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3513),
                            Name = "Aparelhos de Pressão e Massageadores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3513)
                        },
                        new
                        {
                            Id = 83L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3514),
                            Name = "Rastreador de Atividades",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3514)
                        },
                        new
                        {
                            Id = 84L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3515),
                            Name = "Fones Bluetooth",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3515)
                        },
                        new
                        {
                            Id = 85L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3516),
                            Name = "Caixas de Som Portáteis",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3516)
                        },
                        new
                        {
                            Id = 86L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3517),
                            Name = "Adaptadores e Cabos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3518)
                        },
                        new
                        {
                            Id = 87L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3518),
                            Name = "Memórias e Pen Drives",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3519)
                        },
                        new
                        {
                            Id = 88L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3520),
                            Name = "Placas de Vídeo",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3520)
                        },
                        new
                        {
                            Id = 89L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3521),
                            Name = "Processadores",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3521)
                        },
                        new
                        {
                            Id = 90L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3522),
                            Name = "Placas Mãe",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3522)
                        },
                        new
                        {
                            Id = 91L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3523),
                            Name = "Roteadores e Modems",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3523)
                        },
                        new
                        {
                            Id = 92L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3524),
                            Name = "Smart Home",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3524)
                        },
                        new
                        {
                            Id = 93L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3525),
                            Name = "Dispositivos IoT",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3525)
                        },
                        new
                        {
                            Id = 94L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3526),
                            Name = "Produtos Educacionais",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3527)
                        },
                        new
                        {
                            Id = 95L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3527),
                            Name = "Instrumentos Musicais",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3528)
                        },
                        new
                        {
                            Id = 96L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3529),
                            Name = "Material Escolar",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3529)
                        },
                        new
                        {
                            Id = 97L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3530),
                            Name = "Agenda e Planner",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3530)
                        },
                        new
                        {
                            Id = 98L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3531),
                            Name = "Cadernos e Blocos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3531)
                        },
                        new
                        {
                            Id = 99L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3549),
                            Name = "Artigos de Papelaria",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3549)
                        },
                        new
                        {
                            Id = 100L,
                            CreatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3550),
                            Name = "Kits e Combos",
                            UpdatedAt = new DateTime(2025, 10, 18, 19, 34, 17, 533, DateTimeKind.Utc).AddTicks(3551)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("product_category", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("product_category", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("product_category", b =>
                {
                    b.HasOne("Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
